pipeline {
    agent {
      docker {
          image 'node:8.11.1'
      }
    }
    stages {
        stage('Prepare') {
            steps {
                sh 'npm config set registry https://registry.npm.taobao.org && npm install'
            }
        }
        stage('Test e2e') {
            steps {
                retry(2) {
                    sh 'npm run test:e2e'
                }
            }
        }
        stage('Test service') {
            steps {
                sh 'npm run test:service'
            }
        }
        stage('Test unit') {
            steps {
                sh 'npm run test:unit'
            }
        }
        stage('Dashboard') {
            steps {
                sh 'npm run quality'
            }
        }
    }
}
